{{- if .Values.metrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-for-redis.fullname" . }}-metrics
  labels: {{- include "node-for-redis-metrics.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "node-for-redis-metrics.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "node-for-redis-metrics.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "node-for-redis.serviceAccountName" . }}
      containers:
        - name: metrics-server
          image: "{{ .Values.metrics.server.image.repository }}:{{ .Values.metrics.server.image.tag }}"
          imagePullPolicy: {{ .Values.metrics.server.image.pullPolicy }}
          resources: {{- toYaml .Values.metrics.resources | nindent 12 }}
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: CLUSTER_NAME
              value: {{ include "node-for-redis.fullname" . }}
            - name: SERVER_PORT
              value: {{ .Values.metrics.server.port.number | quote }}
          ports:
            - containerPort: {{ .Values.metrics.server.port.number }}
              name: {{ .Values.metrics.server.port.name }}
{{- end }}